// Sample receipt examples with mock data
export const RECEIPT_EXAMPLES = [
    {
        id: "walmart-groceries",
        templateName: "Walmart",
        templateId: "walmart",
        title: "Grocery Shopping Receipt",
        items: [{ name: "Organic Bananas" }, { name: "Whole Milk" }, { name: "Bread" }, { name: "Chicken Breast" }, { name: "Cereal" }],
        itemCount: 12,
        total: 87.43,
        totalFormatted: "$87.43",
        image: "/assets/img/receipts/walmart-thumb.png",
    },
    {
        id: "target-electronics",
        templateName: "Target",
        templateId: "target-receipt",
        title: "Electronics Purchase",
        items: [{ name: "Sony Headphones" }, { name: "USB-C Cable" }, { name: "Phone Case" }],
        itemCount: 3,
        total: 156.99,
        totalFormatted: "$156.99",
        image: "/assets/img/receipts/target-thumb.png",
    },
    {
        id: "louis-vuitton-bag",
        templateName: "Louis Vuitton",
        templateId: "louis-vuitton",
        title: "Luxury Handbag Purchase",
        items: [{ name: "Neverfull MM Tote" }],
        itemCount: 1,
        total: 2030.00,
        totalFormatted: "$2,030.00",
        image: "/assets/img/receipts/louis-vuitton-thumb.png",
    },
    {
        id: "uber-ride",
        templateName: "Uber",
        templateId: "uber-receipt",
        title: "Airport Ride",
        items: [{ name: "UberX to LAX Airport" }],
        itemCount: 1,
        total: 45.67,
        totalFormatted: "$45.67",
        image: "/assets/img/receipts/uber-thumb.png",
    },
    {
        id: "foot-locker-sneakers",
        templateName: "Foot Locker",
        templateId: "foot-locker",
        title: "Air Jordan Purchase",
        items: [{ name: "Air Jordan 4 Retro" }, { name: "Nike Socks 3-Pack" }],
        itemCount: 2,
        total: 234.99,
        totalFormatted: "$234.99",
        image: "/assets/img/receipts/foot-locker-thumb.png",
    },
    {
        id: "walgreens-pharmacy",
        templateName: "Walgreens",
        templateId: "walgreens",
        title: "Prescription & Essentials",
        items: [{ name: "Prescription Rx" }, { name: "Vitamins" }, { name: "First Aid Kit" }],
        itemCount: 5,
        total: 78.24,
        totalFormatted: "$78.24",
        image: "/assets/img/receipts/walgreens-thumb.png",
    },
    {
        id: "costco-bulk",
        templateName: "Costco",
        templateId: "costco",
        title: "Bulk Shopping Trip",
        items: [{ name: "Paper Towels 12-Pack" }, { name: "Kirkland Water" }, { name: "Rotisserie Chicken" }],
        itemCount: 15,
        total: 267.89,
        totalFormatted: "$267.89",
        image: "/assets/img/receipts/costco-thumb.png",
    },
    {
        id: "dior-beauty",
        templateName: "Dior",
        templateId: "dior-receipt",
        title: "Beauty Products",
        items: [{ name: "Womens Shoe" }, { name: "Lip Glow Oil" }],
        itemCount: 2,
        total: 1297.50,
        totalFormatted: "$1,297.50",
        image: "/assets/img/receipts/dior-thumb.png",
    },
    {
        id: "rolex-watch",
        templateName: "Rolex",
        templateId: "rolex",
        title: "Luxury Watch Purchase",
        items: [{ name: "Rolex Submariner Date" }],
        itemCount: 1,
        total: 14550.00,
        totalFormatted: "$14,550.00",
        image: "/assets/img/receipts/rolex-thumb.png",
    },
    {
        id: "stockx-sneakers",
        templateName: "StockX",
        templateId: "stockx-receipt",
        title: "Sneaker Marketplace",
        items: [{ name: "Nike Dunk Low Panda" }],
        itemCount: 1,
        total: 145.00,
        totalFormatted: "$145.00",
        image: "/assets/img/receipts/stockx-thumb.png",
    },
    {
        id: "hotel-stay",
        templateName: "Hotel",
        templateId: "hotel-receipt",
        title: "Weekend Stay",
        items: [{ name: "Room 2 Nights" }, { name: "Room Service" }, { name: "Parking" }],
        itemCount: 3,
        total: 456.78,
        totalFormatted: "$456.78",
        image: "/assets/img/receipts/hotel-thumb.png",
    },
    {
        id: "balenciaga-shoes",
        templateName: "Balenciaga",
        templateId: "balenciaga",
        title: "Designer Sneakers",
        items: [{ name: "Triple S Sneakers" }],
        itemCount: 1,
        total: 1090.00,
        totalFormatted: "$1,090.00",
        image: "/assets/img/receipts/balenciaga-thumb.png",
    },
];

export type ReceiptExample = typeof RECEIPT_EXAMPLES[number];
